name: Build & Deploy

on:
  push:
    branches:
      - main
      - development
      - testing
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && needs.build.result == 'success'
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: 'rufaidae'
      REMOTE_PORT: ${{ secrets.REMOTE_PORT || '22' }}
      BUILD_DIR: 'build'
      REMOTE_DIR: '/home/rufaidae/shop.rufaidaenterprice.com'
      TARGET_URL: 'shop.rufaidaenterprice.com'

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Verify remote directory access
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ env.REMOTE_PORT }} ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} \
            "ls -la ${{ env.REMOTE_DIR }}" || echo "⚠ Remote directory check failed (might be first deployment)"

      - name: Deploy via SSH with backup
        run: |
          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
          ssh -o StrictHostKeyChecking=no -p ${{ env.REMOTE_PORT }} ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} \
            "mkdir -p ${{ env.REMOTE_DIR }}/.backups && \
            tar -czf ${{ env.REMOTE_DIR }}/.backups/backup-$TIMESTAMP.tar.gz -C ${{ env.REMOTE_DIR }} ."
          rsync -avz --progress -e "ssh -p ${{ env.REMOTE_PORT }} -o StrictHostKeyChecking=no" \
            --delete \
            --exclude='.htaccess' \
            --exclude='.well-known/' \
            --exclude='.backups/' \
            ${{ env.BUILD_DIR }}/ ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}:${{ env.REMOTE_DIR }}/
          ssh -o StrictHostKeyChecking=no -p ${{ env.REMOTE_PORT }} ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} \
            "find ${{ env.REMOTE_DIR }} -type d -exec chmod 755 {} \; && \
             find ${{ env.REMOTE_DIR }} -type f -exec chmod 644 {} \;"
          ssh -o StrictHostKeyChecking=no -p ${{ env.REMOTE_PORT }} ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} \
            "find ${{ env.REMOTE_DIR }} -name '*.php' -exec chmod 600 {} \;"

      - name: Verify deployment
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ env.REMOTE_PORT }} ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }} \
            "test -f ${{ env.REMOTE_DIR }}/index.html" || exit 1
          echo "✔ Deployment verified"

      - name: Clear Cloudflare cache (optional)
        if: success()
        uses: jonjohnsonjr/cloudflare-purge@v1
        with:
          zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          urls: |
            https://${{ env.TARGET_URL }}/
            https://${{ env.TARGET_URL }}/index.html
